---
title: "data_wrangling"
author: "Timothy P Morris, PhD"
date: "10/25/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---
#1 taking very messy .csv data and converting it into usable tabular data
# load libraries 
```{r}
library(readr)
library(tidyverse)
```

# import raw data (these .csv files are beahvioral data from HCP-D open access project)
```{r cars}

#read .csv files
#library(readr)

X20200527_SomervilleKramerDataRequest_REDCapChild <- read_csv("20200527_SomervilleKramerDataRequest_REDCapChild.csv")

X20200527_SomervilleKramerDataRequest_REDCapParent <- read_csv("20200527_SomervilleKramerDataRequest_REDCapParent.csv")

SomervilleKramer_RePull_SCORES_Duplicates_Removed_Process <- read_csv("SomervilleKramer RePull SCORES Duplicates Removed Process.csv")

SCORES_clean_wdomnondom <- read_csv("SCORES_clean_wdomnondom.csv") # cleaned some of this data in csv file before importing 

matrix <- read_csv("20200605_ SomervilleKramerDataRequest_REDCapQ-Interactive_MatrixReasoning.csv") # matrix reasoning task results

```
# convert some of these poorly formated .csv files into usable tabluar data
```{r}
# Remove any rows with missing subject ID value
scores <- SCORES_clean_wdomnondom[ !(SCORES_clean_wdomnondom$subject_id %in% NA), ]
# test 

# create long format version of rows with common names to a df with scorename in one column and the actual score value in another
pop2 <- scores %>%
  pivot_longer(`Age-Corrected Standard Score`:`Age-Corrected Standard Scores Non-Dominant`, names_to = "scorename", values_to = "score")

# create a wide version that groups by subject ID. 
pop3 <- pop2 %>% 
  group_by(subject_id, Inst, scorename) %>%
  mutate(rn = row_number()) %>%
  pivot_wider(names_from = Inst, values_from = score)

pop4 <- pop3 %>%
  pivot_wider(
    names_from = scorename,
    names_sep = ".",
    values_from = c(`Cognition Total Composite Score v1.1`:`NIH Toolbox Standing Balance Test Age 7+ v2.0`)
  )

pop5 <- pop4 %>% distinct(subject_id, .keep_all = TRUE)  # removes duplicate rows

# create workable dfs
scores_clean_wide <- pop5
child <- X20200527_SomervilleKramerDataRequest_REDCapChild
parent <- X20200527_SomervilleKramerDataRequest_REDCapParent

```
# filtering 
```{r}
load(file = "hd8.Rdata")
hd8$agecat <- cut(hd8$age, 
                  breaks=c(-Inf, 11.99, 14.99, Inf), 
                  labels=c("elementary","middle","high"))

high <- hd8 %>% dplyr::filter(hd8$age > 14.99) # takes those above this value
middle <- hd8 %>% dplyr::filter(between(hd8$age, 11.99, 14.99)) # takes subjects between two values of the given variable (in this case "age)
elementary <- hd8 %>% dplyr::filter(hd8$age < 11.99) # takes those below this value 

demos <- high %>%
  select(bmi,
         sex,
         educ,
         age,
         SES,
         pds)

demo <- high %>% select(subject_id:bmi)

demos <- demos %>%
    rename("bmi_log" = "bmi")

# remove specific variables from a df
high <- high %>%
  select(-c(pa, cog_fluid))
  
```
#merging
```{r}
# the following functions use dplyr mutate-joins functions 

inner <- inner_join(middle, high)
covarstest <- left_join(middle, high, by = "subjectID")             
covarright <- right_join()
```
# adding and forgetting
```{r}
high <- high$age[-(6),]

fmri_degree_15['meanFD'] <- meanFD146 # append residuals to dataframe 

```
# checking for missing data
```{r}
df <- eela_all %>%
  select(F1_Active_Engagement_goldsmith,
         F2_Perceptual_Abilities_goldsmith,
         F3_Musical_Training_goldsmith,
         bmim0,
         sedTm0)
library(VIM)
aggr_plot <- aggr(df, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))
pMiss <- function(x){sum(is.na(x))/length(x)*100}
apply(df,2,pMiss) # tells me percentage of data that doestn exitss for each var in df
# then remove participants who are missing more than 20% of their data 
apply(df,1,pMiss) # tells me which samples (participants) are missing more than one data piece (in this case 60 measn 3 out of 5 vars are missing for some samples)
#create tibble with comeplte data and no feature reduction 
```

